export const ORDER_CONSTANTS = {
  MAX_SEARCH_DISTANCE_METERS: 50000, // 50km
  EARTH_RADIUS_METERS: 6371000,
  SCORING: {
    DISTANCE_WEIGHT: 50,
    RATING_WEIGHT: 30,
    AVAILABILITY_WEIGHT: 20,
    MAX_RATING: 5,
    BASE_DISTANCE_FACTOR: 5000,
  },
  DEFAULT_RESPONSE_TIMEOUT_MINUTES: 15,
};
